[package]
name = "shadowcast"
description = "Implementation of the recursive shadowcast visible-area detection algorithm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
documentation = "https://docs.rs/shadowcast"
repository = "https://github.com/stevebob/shadowcast.git"
homepage = "https://github.com/stevebob/shadowcast.git"
readme = "README.md"

[dependencies]
direction = "0.13"
grid_2d = "0.7"
num = "0.1"
